#!/bin/sh
set -e
export LC_ALL=C

#scripts/fribidi-config
#scripts/fribidi-build "$@"
scripts/libplacebo-config
scripts/libplacebo-build "$@"
scripts/libass-config
scripts/libass-build "$@"
scripts/ffmpeg-config
scripts/ffmpeg-build "$@"

if test -d libplacebo/3rdparty/Vulkan-Headers/include ; then
    mkdir -p build_libs/include
    cp -a libplacebo/3rdparty/Vulkan-Headers/include/. build_libs/include/
fi

scripts/mpv-config
scripts/mpv-build "$@"
